### ISSUE TITLE
local images / wiki-links?

### ISSUE THREAD

**Issue by berot3** [HananoshikaYomaru/obsidian-image-caption#2]
so this not for the average image-linking to local files through `![[image.png|caption]]`? so that I can use the plugin also by simply writing

```
%% ![[image.png|caption]] %%

or

%% caption ![[image.png]] %%
```

is it intended for external images only?

or is it maybe something on/for the roadmap? :)

**Comment by HananoshikaYomaru** [comment]
yes, sorry I should put this in the doc. this is only for external images. I am not using local images so I don't plan to support this. I would be glad if someone else help implement this feature.
